# Conditions.
.only_web_feature: &only_web_feature
  rules:
    - changes:
        - web/**/*
      if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

.only_web_tag_release: &only_web_tag_release
  rules:
    - if: $CI_COMMIT_TAG =~ /^web\/[0-9.]+$/

# Jobs templates.
.build_definition: &build_definition
  image: docker:20.10.12
  stage: build
  services:
    - docker:dind
  script:
    - apk add --no-cache bash
    - bash ./web/packages/ce/ci_docker_build_push.sh

# Jobs.
build_basic_image_release:
  <<: *build_definition
  <<: *only_web_tag_release
  variables:
    REGISTRY_USER: "${DH_CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${DH_CI_REGISTRY_PASSWORD}"
    REGISTRY: "${DH_CI_REGISTRY}"
    DOCKER_NAME: "postgresai/ce-ui"
  before_script:
    - export WEB_VERSION=$(echo ${CI_COMMIT_TAG#"web/"})
    - export TAGS="${DOCKER_NAME}:${WEB_VERSION},${DOCKER_NAME}:latest"

build_basic_image_dev:
  <<: *build_definition
  <<: *only_web_feature
  variables:
    REGISTRY_USER: "${CI_REGISTRY_USER}"
    REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    REGISTRY: "${CI_REGISTRY}"
    DOCKER_NAME: "registry.gitlab.com/postgres-ai/database-lab/ce-ui"
    TAGS: "${DOCKER_NAME}:${CI_COMMIT_REF_SLUG}"
  when: manual
